theme: jekyll-theme-cayman
title: Iowa Community Blueprints
description: Strong, independent support networks right on our streets and rural roads, free from red tape, complex laws, or corporate influence.